import * as React from "react";

import { EmailButton, EmailCard, EmailLayout } from "@/emails/components/email-layout";
import { formatInTZ, formatTimeZoneLabel } from "@/lib/utils/timezone";

interface AppointmentInviteEmailProps {
  patientName: string;
  patientEmail?: string;
  therapistName: string;
  locationAddress: string;
  bookingNumber: string;
  notes?: string;
  start: Date;
  end: Date;
  googleCalendarUrl?: string;
  language?: "es" | "en";
  timeZone: string;
}

export function AppointmentInviteEmail({
  patientName,
  patientEmail,
  therapistName,
  locationAddress,
  bookingNumber,
  notes,
  start,
  end,
  googleCalendarUrl,
  language = "es",
  timeZone,
}: Readonly<AppointmentInviteEmailProps>) {
  const isSpanish = language === "es";
  const locale = isSpanish ? "es-MX" : "en-US";

  const t = {
    title: isSpanish ? "Solicitud de Cita" : "Appointment Request",
    intro: isSpanish
      ? "Se ha solicitado la siguiente cita:"
      : "The following appointment has been requested:",
    patient: isSpanish ? "Participante" : "Participant",
    bookingNumber: isSpanish ? "Codigo de cita" : "Booking number",
    email: isSpanish ? "Correo" : "Email",
    therapist: isSpanish ? "Profesional" : "Professional",
    when: isSpanish ? "Cuándo" : "When",
    timeZone: isSpanish ? "Zona horaria" : "Time zone",
    where: isSpanish ? "Dónde" : "Where",
    notesLabel: isSpanish ? "Notas" : "Notes",
    addToCalendar: isSpanish ? "Añadir a Calendario" : "Add to Calendar",
    footer: isSpanish
      ? "Este mensaje fue generado automáticamente por el sistema de solicitudes de citas."
      : "This message was automatically generated by the booking system.",
  };

  const dateLine = formatInTZ(start, "EEEE dd MMMM yyyy", timeZone);
  const timeLine = `${formatInTZ(start, "hh:mm a", timeZone)} – ${formatInTZ(end, "hh:mm a", timeZone)}`;
  const timeZoneLine = formatTimeZoneLabel(timeZone, locale);

  return (
    <EmailLayout
      eyebrow="AlphaBioHack"
      title={t.title}
      intro={t.intro}
      footer={t.footer}
    >
      <div>
        <div style={{ marginBottom: "20px" }}>
          <EmailCard>
            <p style={{ margin: 0, fontSize: "14px", color: "#334155", lineHeight: 1.7 }}>
              <strong>{t.patient}:</strong> {patientName}
            </p>
            <p style={{ margin: 0, fontSize: "14px", color: "#334155", lineHeight: 1.7 }}>
              <strong>{t.bookingNumber}:</strong> {bookingNumber}
            </p>
            {patientEmail ? (
              <p style={{ margin: 0, fontSize: "14px", color: "#334155", lineHeight: 1.7 }}>
                <strong>{t.email}:</strong>{" "}
                <a
                  href={`mailto:${patientEmail}`}
                  style={{ color: "#0b5cab", textDecoration: "none" }}
                >
                  {patientEmail}
                </a>
              </p>
            ) : null}
            <p style={{ margin: 0, fontSize: "14px", color: "#334155", lineHeight: 1.7 }}>
              <strong>{t.therapist}:</strong> {therapistName}
            </p>
            <p style={{ margin: 0, fontSize: "14px", color: "#334155", lineHeight: 1.7 }}>
              <strong>{t.when}:</strong> {dateLine} · {timeLine}
            </p>
            <p style={{ margin: 0, fontSize: "14px", color: "#334155", lineHeight: 1.7 }}>
              <strong>{t.timeZone}:</strong> {timeZoneLine}
            </p>
            <p style={{ margin: 0, fontSize: "14px", color: "#334155", lineHeight: 1.7 }}>
              <strong>{t.where}:</strong> {locationAddress}
            </p>
          </EmailCard>
        </div>

        {notes ? (
          <div style={{ marginBottom: "20px" }}>
            <EmailCard tone="accent">
              <h2 style={{ margin: "0 0 10px 0", fontSize: "18px", color: "#0f172a" }}>
                {t.notesLabel}
              </h2>
              <p
                style={{
                  margin: 0,
                  color: "#334155",
                  fontSize: "14px",
                  lineHeight: 1.7,
                  whiteSpace: "pre-wrap",
                }}
              >
                {notes}
              </p>
            </EmailCard>
          </div>
        ) : null}

        {googleCalendarUrl ? (
          <EmailButton href={googleCalendarUrl}>{t.addToCalendar}</EmailButton>
        ) : null}
      </div>
    </EmailLayout>
  );
}
